# Generated by Django 4.0 on 2021-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='devices',
            field=models.ManyToManyField(blank=True, to='base.Device'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='time',
            field=models.ManyToManyField(blank=True, to='base.TimeBook'),
        ),
    ]
