# Generated by Django 4.0 on 2021-12-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_alter_desk_devices_alter_desk_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
