# Generated by Django 4.0 on 2021-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_desk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='user',
        ),
        migrations.AddField(
            model_name='desk',
            name='name_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='desk',
            name='phone_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='desk',
            name='surname_user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
